### ISSUE TITLE
Scaling Questions

### ISSUE THREAD

**Issue by lonnieOST** [jivesearch/jivesearch#103]
Hello,

Hope that you are doing well today. 

I have recently come across the Jivesearch engine while researching the current state-of-the-art efforts in this area and like what I have seen so far. Great job!!!

One question that I have in in regard to scaling of the data store.  Currently, I see that you use Elasticsearch, PostgreSQL, and Redis  in a very complex Golang project.

Could you please tell me more about how the data is stored since I would guess that a majority of the main data is within the Elasticsearch database, right?

If that is so, then how hard would it be to change things over to use an Elasticsearch cluster in which scaling would be as easy as adding more nodes, or do you also need to cluster the PostgreSQL and Redis nodes as well?

Along these lines, I would also think that if the databases were setup into perspective clusters then it might be easy to have the Jivesearch frontends running on different  physical servers that could be handled by a load balancer and support a number of multiple users on the service.

Mostly just trying to get a feel for what Jivesearch could be capable of doing on a scaling basis and any information would be greatly appreciated.

Cheers :)

**Comment by brentadamson** [comment]
Most of the changes that would need to be made would be in our executable package: https://github.com/jivesearch/jivesearch/blob/master/frontend/cmd/frontend.go. We'd also likely have to make some changes to our configuration variables also: https://github.com/jivesearch/jivesearch/blob/master/config/config.go.

We're monitoring each service and will make changes as needed.

**Comment by lonnieOST** [comment]
Thanks for the reply, Brent

I am trying to build things now from scratch in a Docker container. It
seems to be a long build process.

Could you please let me know what each of the database are used for, in
general:

Elasticsearch
PostgreSQL
Redis

Thanks again and have a great day
Lonnie

**Comment by lonnieOST** [comment]
One more quick question, Brent.

I noticed that you are using the Yandex as the provider and I was wondering
if the results from the provider is stored in the Jivesearch database as
well for future similar queries?
Thanks again

**Comment by brentadamson** [comment]
The majority of the time is spent building our NSFW image classification server for our images (we need a lot of improvement there as our image search is terrible right now). Also, NGINX build takes a little while since we have a custom build there for the pagespeed module. Elasticsearch is used for the core search results (unless you use Yandex). It is also used for the autocomplete. PostgreSQL is used for Musicbrainz and Wikipedia. Redis is used for the cache.

No, we don't store the Yandex results in ES.

Let me know if you run into any issues.

**Comment by lonnieOST** [comment]
Thanks again and I'll let you know how the build goes.

Just a thought thought. Wouldn't it be beneficial for results coming back
from external providers to be stored and indexed for future use?  I could
think of a case where a Metasearch engine might be called as a provider and
then multiple users might have similar queries at different times in which
partial results could already be in the Jivesearch database. Just playing
with ideas though.

Cheers :)

**Comment by brentadamson** [comment]
It is cached with Redis. There is an open issue #60 to make the search provider flexible for the user. If we were to mix providers I think ES would be a bit overkill and we could accomplish the same with Redis...we wouldn't want the results to get stale.

**Comment by brentadamson** [comment]
Contact me in our chatroom if you have any issues setting up.

**Comment by lonnieOST** [comment]
Let me find out were your chat room is and perhaps we can chat more there.
Thanks again we can close this issue now.

**Comment by brentadamson** [comment]
https://discord.gg/cfxQkuh
