### ISSUE TITLE
Wikidumper: Unexpected end of line (JSON)

### ISSUE THREAD

**Issue by thedumbestdinosaur** [jivesearch/jivesearch#121]
Hi, I have successfully setup the project locally but halfway through the wikidumps I am receiving an error stating unexpected end of line, is this project up-to-date with the latest format of wiki dumps or do we need to rollback the downloads we're using to an older dump or is this issue only for me? many thanks in advance.

**Comment by brentadamson** [comment]
Hard to know without more details. The easy fix would be to use an older dump file but then you'll have out of date Wikipedia answers. It's better to find where it's failing and correct it. Just wish I had more time these days to dive in. Can you post the stacktrace?

**Comment by brentadamson** [comment]
Without knowing more details I can take a guess that they may have added some test files that need to be skipped over. If that's the case then you can append that item to the slice at: https://github.com/jivesearch/jivesearch/blob/master/instant/wikipedia/dump.go#L285.

**Comment by thedumbestdinosaur** [comment]
thanks for the help.
It is definitely an issue with the new wave of wiki dumps (not sure when the issue started) but for anyone wanting a quick fix; changing line 207-209 of dump.go works:
`var reWikipedia = regexp.MustCompile(`^([a-z_]+)wiki-20171218-cirrussearch-content.json.gz$`)
var reWikiquote = regexp.MustCompile(`^([a-z_]+)wikiquote-20171218-cirrussearch-content.json.gz$`)
var reWiktionary = regexp.MustCompile(`^([a-z_]+)wiktionary-20171218-cirrussearch-content.json.gz$`)`

obviously its a super out-of-date dump but I haven't got the time to backcheck the last working dump, im going to try and find the cause of the issue but im a novice gopher so if you could find time to take a look too it would be appreciated :)

**Comment by thedumbestdinosaur** [comment]
It is definitely an issue with the new wave of wiki dumps (I'm not sure when this issue started) backdating the dumps worked but as you mentioned, the answers are now out of date. 
The stack trace is no help, I don't know where you usually find your wiki info but I can't find any mention of any breaking changes to the structure and no panics from mis-formed/unhandled tags so if you could find as time to look deeper into this, I'd appreciate it.
For now, we must use an older dump.
