### ISSUE TITLE
Crawler issues

### ISSUE THREAD

**Issue by rizzoid** [jivesearch/jivesearch#13]
The crawler will continue to ping remote URLs even when there are issues being reported by the Elasticsearch backend, such as when disk space runs low and it switches to read-only mode. While I missed the error from the crawler, this will will be output from the search side:

`INFO 2018/04/29 00:16:04 search.go:327: elastic: Error 403 (Forbidden): blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]; [type=cluster_block_exception]`

It might be better to trap this condition and report on its cause, then exit gracefully, or perhaps catch it in the search subsystem when this shows up in the logs:

Also related: the crawler will error out when the Elasticsearch daemon goes offline.

**Comment by brentadamson** [comment]
I haven't run into either case yet. Probably could test by manually shutting off Elasticsearch mid-crawl. It should be panicking in the event of an ES error, no? https://github.com/jivesearch/jivesearch/blob/master/search/crawler/cmd/crawler.go#L35-L37.

I've actually been thinking about replacing our crawler with Colly (https://github.com/gocolly/colly) for performance reasons. Colly came out b/f I launched this repo but after I had written the crawler portion.

**Comment by rizzoid** [comment]
Indeed, it does panic.

And Colly looks quite nice and it's obviously quite robust and actively being developed, which would leave more time for this project to focus on the frontend side of the search equation.

**Comment by brentadamson** [comment]
I'm a bit confused...does it continue on or panic when ES is down/disc space runs low?

**Comment by brentadamson** [comment]
I understand the issue now....nevermind. I've also run into that issue on the frontend but missed it on the crawler. I'd rather not exit for the frontend as the users would then be unable to use !bangs & instant answers. 

For the second case where the ES goes offline:
When I stop elasticsearch mid-crawl it panics, as expected:

    panic: no available connection: no Elasticsearch node available
    
    goroutine 11 [running]:
    main.afterFn(0x3, 0xc423d78000, 0x3e8, 0x400, 0x0, 0xd65560, 0xc42c596a40)
    ...
    ...
    exit status 2

Should we instead exit gracefully?

**Comment by brentadamson** [comment]
Please reopen if issues continue
