### ISSUE TITLE
Custom branding with SVG-generated image logos produces undesirable results

### ISSUE THREAD

**Issue by rizzoid** [jivesearch/jivesearch#14]
With the fix-width specified for the custom-generated SVG image when a custom brand name is specified, it can produce other-than-intended results, such as:

- Off center text if the name is shorter than "Jive Search'.
- Clipping on the right side if the name is longer.

**Comment by brentadamson** [comment]
Have you tried adjusting the width attribute of the <svg> tag and then adjusting the "x" attribute of the <text> element?

**Comment by brentadamson** [comment]
Can you post examples that break it?

**Comment by tdannecy** [comment]
@rizzoid Can you post a screenshot?

**Comment by rizzoid** [comment]
I'll just submit a patch this evening.
