### ISSUE TITLE
Move bang data to database?

### ISSUE THREAD

**Issue by rizzoid** [jivesearch/jivesearch#18]
Given the large number of bang items that could potentially be added, it would seem to make more sense to move them to the database at some point. For example, Duck Duck Go has over 10,000 of them. Even with  just a fraction of those implemented at a few lines each, that's a _lot_ of code to be moving around whereas it could potentially just be a single line in a SQL file.

(Side note: feature requests as issues with tags, elsewhere, or what?)

**Comment by brentadamson** [comment]
That would be a very long line...how about a config file and then they could be customized? (Alternatively, we could add a method to override a !bang). Some people have really strong opinions on some of them, especially those with single characters.

**Comment by rizzoid** [comment]
Whops, I didn't clarify that very well: I meant to say that each bang search could be a single line instead of multiple lines of code as you'd remove all that duplication by iterating over the raw data.

And I'm alright with config files. With a sufficient number of bang search types, anything would likely be superior to have them all directly in raw Go.

**Comment by brentadamson** [comment]
Why don't we try the config first and see how it goes? We could put the default config file in the bangs package then let the caller unmarshall to the bangs.Bangs struct. That way, the caller can decide to use some other config file and/or change the bangs w/in the Bangs slice. 

If that sounds ok, should we use TOML? JSON? I kind of like TOML since it's pretty straightforward but I'm open.

**Comment by rizzoid** [comment]
TOML for human-edited text gets my vote, and that's what this file is right now.

**Comment by brentadamson** [comment]
Have you started on this, then? If not I can.

**Comment by rizzoid** [comment]
I won't be able to tackle much for at least a few weeks due to work and other commitments. Bite-sized tasks are more my speed at the moment.

**Comment by brentadamson** [comment]
OK...just wanted to make sure b/f I went ahead.
