### ISSUE TITLE
Chat room?

### ISSUE THREAD

**Issue by clanstyles** [jivesearch/jivesearch#2]
Does JiveSearch have a chat room? I'd love to contribute. Do you have a road map?

**Comment by brentadamson** [comment]
Good to hear! No chatroom yet. Any suggestions? Initial roadmap is to get the structure right and then adding !bangs, IA's should be pretty easy. Need to speed it up...the speed of the core search results needs to improve as well as the relevancy when there are no votes. I would like to make the crawler more configurable/modular and improve the speed as well...it tends to really slow down after 5-10 minutes. Those are my initial thoughts. Eventually will be adding image search, maps, etc. I'm not a developer by nature (but I'm not completely new) so I'm looking for feedback on everything...the layout, privacy improvements, etc.

**Comment by clanstyles** [comment]
Not sure, a lot of things are popular right now. Discord for voice, Slack, Gitter.

**Comment by brentadamson** [comment]
I've never used any of them so I don't really have a preference. Let's try Discord: https://discord.gg/cfxQkuh

**Comment by brentadamson** [comment]
We'll do Discord for now. https://discord.gg/cfxQkuh

Once we need something more we can switch to Discourse. Caddy uses Discourse and I like the categories: https://caddy.community/. 

https://caddyserver.com/blog/new-community-forum.html

**Comment by brentadamson** [comment]
I've added a road map to the readme.

**Comment by brentadamson** [comment]
I have the chatroom up & running but so far I've been the only one there ;(.
