### ISSUE TITLE
README.md suggestions

### ISSUE THREAD

**Issue by adamfaliq42** [jivesearch/jivesearch#23]
@brentadamson , can you write some descriptions on how Jive Search works? I think it would be great if you explain how it solves privacy problem and differs from other search engines as well?

Some other things to add:
1.  Logo
2. Translations
3. Test section

Thanks!

**Comment by brentadamson** [comment]
Can you clarify what you mean by Translations?

**Comment by adamfaliq42** [comment]
Translating the README.md to other languages, namely Chinese and French

**Comment by brentadamson** [comment]
Yes! If someone wants to do that then please do! 

I do think we need to expand on the privacy features but I don't want to make the README.md too long. We can put that in the /about page then link to that in README.md.

**Comment by adamfaliq42** [comment]
I have added these tasks to README.md. Will close the issue now.
