### ISSUE TITLE
No Calculations Work

### ISSUE THREAD

**Issue by GalanJ** [jivesearch/jivesearch#26]
http://prntscr.com/jd4ebw

I tried adding, subtracting, multiplying, and dividing. None of them work.

**Comment by adamfaliq42** [comment]
Similar to issue #6

**Comment by brentadamson** [comment]
The current trigger for the calculator is either "calculator" or "calculate". We should expand the triggers to include math formulas like you have in your query.

**Comment by brentadamson** [comment]
Also, when someone types in a math formula like "1+1" we should also provide the answer via Go in case javascript is disabled. And if javascript is disabled then don't show the calculator since it would be worthless.

**Comment by brentadamson** [comment]
For the actual go formula we could use something like https://github.com/Knetic/govaluate and we could just pass in the entire query e.g. `20+10`. I'm still not sure about the regex here that would trigger complex formulas....maybe just always trigger it and if the result is not a number then continue on with the other instant answers.

**Comment by brentadamson** [comment]
I believe this is resolved. Please reopen if there are any issues.
