### ISSUE TITLE
Move config into external file

### ISSUE THREAD

**Issue by rizzoid** [jivesearch/jivesearch#39]
Move configuration out of config/config.go and push into a config-sample.toml and import with Viper. Add note to project README, and error gracefully if a config.toml isn't found.

Two benefits: doesn't overwrite data on repo refresh and another step towards a proper deployment setup.

**Comment by brentadamson** [comment]
Can you clarify the part on "doesn't overwrite data on repo refresh"? All customization is set via env variables.
