### ISSUE TITLE
NSFW autocomplete suggestions

### ISSUE THREAD

**Issue by valencik** [jivesearch/jivesearch#82]
It's currently quite easy to get NSFW suggestions with only single key inputs.
Consider `curl 'https://jivesearch.com/autocomplete?q=p'` which currently returns numerous troubling suggestions.

**Comment by brentadamson** [comment]
Yeah, this needs to be taken care of but I'm not really sure how. As our traffic grows this should kind of take care of itself, since the autocomplete results are weighted by popularity but I'd like to find a solution b/f then.

**Comment by brentadamson** [comment]
Here's an option with multiple languages: https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words

**Comment by brentadamson** [comment]
Turns out it was a lot easier than I originally thought as I didn't think a multi-language list like that existed. For those running their own instances you will have to delete your autocomplete index `curl -XDELETE localhost:9200/test-queries` then restart the frontend.
