### ISSUE TITLE
[Question] Where do the search results come from?

### ISSUE THREAD

**Issue by gjhklfdsa** [jivesearch/jivesearch#90]
**Question**: Where does Jive Search get its search results (Example: [Yahoo](https://www.wikipedia.org/wiki/Yahoo!_Search), [Yandex](https://www.wikipedia.org/wiki/Yandex_Search), [Bing](https://www.wikipedia.org/wiki/Bing_(search_engine)), [Google](https://www.wikipedia.org/wiki/Google_Search), e.c.t)?

**Comment by brentadamson** [comment]
The search provider is flexible. jivesearch.com uses Yandex but if you're running your own instance you can have your own results if you want by running the crawler. Other search providers can easily be added as it is an interface.

**Comment by brentadamson** [comment]
There's also #60
